veux: Fix HAL compatibility in device manifest: Update FCM <= level 6
All HALs in device manifest are declared in FCM <= level 6
ERROR: files are incompatible: Framework manifest and device compatibility matri
x are incompatible: HALs incompatible. The following requirements are not met:
android.frameworks.schedulerservice:
    required: @1.0::ISchedulingPolicyService/default
    provided:
: Success