veux: Fix HAL version conflicts in device manifest  & Satisfy FCM
following HALs in device manifest are not declared in FCM <= level 6:
  android.hardware.light.ILights/default (@2)
ERROR: files are incompatible: android.hardware.radio@1.5::IRadio/slot1 is deprecated; requires at least 1.6
    because it matches android.hardware.radio@1.4::IRadio/slot1 from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.radio@1.5::IRadio/slot2 is deprecated; requires at least 1.6
    because it matches android.hardware.radio@1.4::IRadio/slot2 from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.radio@1.5::IRadio/slot1 is deprecated; requires at least 1.6
    because it matches android.hardware.radio@1.5::IRadio/slot1 from /system/etc/vintf/compatibility_matrix.5.xml
android.hardware.radio@1.5::IRadio/slot2 is deprecated; requires at least 1.6
    because it matches android.hardware.radio@1.5::IRadio/slot2 from /system/etc/vintf/compatibility_matrix.5.xml: Success
INCOMPATIBLE

Signed-off-by: Amrito | アンブロシア <bhabanidas431@gmail.com>